name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nginx_version:
          - 1.22.1
          - 1.24.0
          - 1.25.3

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download NGINX sources
        run: |
          nginx="nginx-${{ matrix.nginx_version}}.tar.gz"
          wget https://nginx.org/download/${nginx}.asc
          wget https://nginx.org/download/${nginx}
          gpg --recv-keys 13C82A63B603576156E30A4EA0EA981B66B0D967
          gpg --verify ${nginx}.asc
          tar -xzf ${nginx}

      - name: Compile
        working-directory: "nginx-${{ matrix.nginx_version }}"
        env:
          GUILE_MODULE_PATH: ${{ env.GITHUB_WORKSPACE }}
        run: |
          ./configure --add-module=$GUILE_MODULE_PATH
          make
