name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nginx_version:
          - 1.22.1
          - 1.24.0
          - 1.25.3

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download NGINX sources
        run: |
          nginx="nginx-${{ matrix.nginx_version }}.tar.gz"
          wget -q https://nginx.org/download/${nginx}.asc
          wget -q https://nginx.org/download/${nginx}
          gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 13C82A63B603576156E30A4EA0EA981B66B0D967
          gpg --verify ${nginx}.asc
          tar -xzf ${nginx}

      - name: Install dependencies
        run: |
          sudo apt install pkg-config guile-3.0-dev guile-3.0-libs

      - name: Compile
        working-directory: "nginx-${{ matrix.nginx_version }}"
        run: |
          ./configure --add-module=..
          make
