name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nginx_version:
          - 1.22.1
          - 1.24.0
          - 1.25.3

    steps:

      - name: Download NGINX sources
        env:
          NGINX_ARCHIVE: "nginx-${{ matrix.nginx_version}}.tar.gz"
        run: |
          wget https://nginx.org/download/$NGINX_ARCHIVE
          tar -xzf $NGINX_ARCHIVE
          
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Compile
        working-directory: "nginx-${{ matrix.nginx_version }}"
        env:
          GUILE_MODULE_PATH: ${{ env.GITHUB_WORKSPACE }}
        run: |
          ./configure --add-module=$GUILE_MODULE_PATH
          make
